### ISSUE TITLE
Creating a window with gosu

### ISSUE THREAD

**Issue by AlexBecthold** [noahc/learn_gosu#10]
At the start of the book, we need to first open a window so we can do anything with a game.  Our very first command is 

```
require 'gosu'
```

But for some reason I'm running into an issue with this.  I believe I installed gosu with a command I found online, but it didn't seem to make any difference.

```
stantonstudent@stantonstudent-VirtualBox:~/Desktop/Games/WhackARuby$ sudo apt-get install build-essential libsdl2-dev libsdl2-ttf-dev libpango1.0-dev \
>                      libgl1-mesa-dev libfreeimage-dev libopenal-dev libsndfile-dev
```

Why am I having this issue?

**Comment by noahc** [comment]
apt-get installs linux packages. Gosu is a ruby gem so it can't be installed via apt-get. You need to do something like `gem install gosu` to get it working.

**Comment by AlexBecthold** [comment]
That worked to install the gem, but I still get the same issue when trying to run the whack_a_mole.rb

**Comment by AlexBecthold** [comment]
```
stantonstudent@stantonstudent-VirtualBox:~/Desktop/Games/WhackARuby$ ruby whack_a_ruby.rb 
/home/stantonstudent/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- gosu (LoadError)
    from /home/stantonstudent/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from whack_a_ruby.rb:1:in `<main>'

```

**Comment by noahc** [comment]
what does `which ruby` give you?

**Comment by AlexBecthold** [comment]
```
/home/stantonstudent/.rvm/rubies/ruby-2.2.1/bin/ruby
```

**Comment by AlexBecthold** [comment]
Do I have the wrong version of ruby?

**Comment by noahc** [comment]
The version shouldn't really matter. You've got a modern enough ruby. I just wanted to make sure you're using the RVM ruby and not the system ruby.

**Comment by noahc** [comment]
Did you run 'gem install gosu' in the directory of your project? If not you might try that, although, I don't think that is your issue.

**Comment by AlexBecthold** [comment]
I did run that and it installed fine.  It says in the book to download the developer tools from the ruby website as well.  I think I did but could that be the issue?

**Comment by noahc** [comment]
The developer tools are windows specific.

**Comment by noahc** [comment]
Just to be more clear, they are Windows specific, so you shouldn't need to install them on Linux.

**Comment by noahc** [comment]
I'm able to reproduce this issue, so that's a start....

**Comment by AlexBecthold** [comment]
Could there be an issue if I downloaded the gosu gem while in the wrong directory?  Do I need to be in a specific place while doing that or does that matter?

**Comment by AlexBecthold** [comment]
I believe I was in the Games folder of the WhackARuby folder when I downloaded

**Comment by noahc** [comment]
You need to install the Gosu gem to the specific ruby being executed. One way to do that is to make sure you're in the same directory as the file you want to execute. In this case be in the same directory that `whack_a_mole.rb` is in.

**Comment by noahc** [comment]
I just did `sudo apt-get install build-essential libsdl2-dev libsdl2-ttf-dev libpango1.0-dev libgl1-mesa-dev libfreeimage-dev libopenal-dev libsndfile-dev`

and then `gem install gosu`

and then `vim gosu.rb`

and then added just `require 'gosu'` to the file

and then `ruby gosu.rb` 

and it worked. 

Try that in your home directory and see what happens.

**Comment by AlexBecthold** [comment]
I installed the gem in the correct folder, and it finally worked.  I have a couple questions about this though.  Will I need to re-install gosu in every  game folder that I create for this to work? And also, the window appears but there are some errors in the terminal when it first comes up

```
stantonstudent@stantonstudent-VirtualBox:~/Desktop/Games/WhackARuby$ ruby whack_a_ruby.rb 
pci id for fd 9: 80ee:beef, driver (null)
libGL error: core dri or dri2 extension not found
libGL error: failed to load driver: vboxvideo
pci id for fd 9: 80ee:beef, driver (null)
libGL error: core dri or dri2 extension not found
libGL error: failed to load driver: vboxvideo
```

I'll try what you did next

**Comment by noahc** [comment]
You will need to install gosu in every game folder that uses a different ruby and gemset combo.

You can figure out what you have installed and are using by running theses two commands: `rvm gemset list` and `rvm list`

Those errors are caused by using virtual hardware. Does it cause the app to crash? I believe if you go into the virtual box settings and turn off 3d acceleration that will stop those form showing up.

**Comment by AlexBecthold** [comment]
It doesn't crash due to the errors, they just show up.  I'll try it without 3d acceleration

**Comment by AlexBecthold** [comment]
I don't think I have it turned on.  I looked in settings and it was grayed out so I couldn't click on it.

**Comment by AlexBecthold** [comment]
As long as those messages won't effect anything, I don't think it should matter too much.
