### ISSUE TITLE
How to update files

### ISSUE THREAD

**Issue by AlexBecthold** [noahc/learn_gosu#6]
I'm starting to work on the assignments for module 1.  I went through the process for committing a file in episode 2, but I was wondering how we are to update these files.  Will they automatically update as we are saving the files on our computers?  Or will we have to commit the files only when they are finished or commit them again if we have any changes to make?  My first three commits were just a test to get used to the process.  Thank you!

**Comment by noahc** [comment]
No, they won't automatically update. You'll follow a similar process to what you already are doing. It will look something like this:

```
# make change to already existing file
git add path/to/file
git commit -m 'I fixed a typo'
git push
```

**Comment by AlexBecthold** [comment]
Thank you!  I didn't think that they would, but I figured I would just make sure.
